title: "bash初心者脱出レシピ"
summary: "bashスクリプト付き"
topics: ["Linux", "bash", "Unix", "macOS"]
published: false
price: 500 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - reverse
  - temporary
  - loop
  - grep
  - sed
  - awk
  - getopt
  - expect
  - deepl_translate
  - slack
