title: "Powershell入門"
summary: "windowsユーザーもその他のユーザーにも役立つ"
topics: ["powershell", "windows", "dotnet"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう

ネットにない情報をメインに書いていく感じ。
マイペースに定期的に追加していきます。


chapters:
  - version
  # - variable
  # - function
  # - environment
