title: "Powershell入門"
summary: "windowsユーザーもその他のユーザーにも役立つ"
topics: ["powershell", "windows", "dotnet"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう

chapters:
  - init
  - version
  - variable
  - if
  # - variable
  # - function
  # - environment
